apiVersion: apps/v1
kind: Deployment
metadata:
  name: descuentopersonas-service
  labels:
    app: descuentopersonas-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: descuentopersonas-service
  template:
    metadata:
      labels:
        app: descuentopersonas-service
    spec:
      containers:
      - name: descuentopersonas-service
        image: pelucap/microservicios:descuentopersonas-service
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-server:8888
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "descuentopersonas-service"
        - name: EUREKA_INSTANCE_INSTANCEID
          value: "descuentopersonas-service:${HOSTNAME}"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/descuentopersonas
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
---
apiVersion: v1
kind: Service
metadata:
  name: descuentopersonas-service
  labels:
    app: descuentopersonas-service
spec:
  selector:
    app: descuentopersonas-service
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP