apiVersion: apps/v1
kind: Deployment
metadata:
  name: reportes-service
  labels:
    app: reportes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reportes-service
  template:
    metadata:
      labels:
        app: reportes-service
    spec:
      containers:
      - name: reportes-service
        image: pelucap/microservicios:reportes-service
        ports:
        - containerPort: 8092
          name: http
        env:
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://config-server:8888
        - name: SPRING_CONFIG_IMPORT
          value: optional:configserver:http://config-server:8888
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://eureka-server:8761/eureka/
        - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
          value: "true"
        - name: EUREKA_INSTANCE_HOSTNAME
          value: "${HOSTNAME}.reportes-service"
        - name: EUREKA_INSTANCE_INSTANCEID
          value: "${HOSTNAME}:${spring.application.name}:${random.value}"
        - name: SPRING_CLOUD_CONFIG_FAIL_FAST
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: reportes-service
  labels:
    app: reportes-service
spec:
  selector:
    app: reportes-service
  ports:
  - port: 80
    targetPort: http
  type: ClusterIP