server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PelucaP/KartingMicroservicios
          default-label: main
          search-paths: '*'  # Search all subdirectories