server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # This allows lowercase service IDs in URLs
      routes:
        - id: reservacomprobante-service
          uri: lb://reservacomprobante-service  # This uses Eureka for discovery and load balancing
          predicates:
            - Path=/api/reserva/**  # This matches your actual controller paths

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
