server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true  # This allows lowercase service IDs in URLs
      routes:
        - id: reservacomprobante-service
          uri: lb://reservacomprobante-service  # This uses Eureka for discovery and load balancing
          predicates:
            - Path=/api/reserva/**  # This matches your actual controller paths
        - id: descuentopersonas-service
          uri: lb://descuentopersonas-service  # This uses Eureka for discovery and load balancing
          predicates:
            - Path=/api/descuento/**  # This matches your actual controller paths
        - id: tarifa-service
          uri: lb://tarifa-service
          predicates:
            - Path=/api/tarifa/**
        - id: tarifas-especiales-service
          uri: lb://tarifas-especiales-service
          predicates:
            - Path=/api/tarifaespecial/**
        - id: descuentos-frecuencia-service
          uri: lb://descuentos-frecuencia-service
          predicates:
            - Path=/api/frecuencia/**

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
