server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: descuentopersonas-service
  datasource:
      url: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver