server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health

spring:
  application:
    name: descuentopersonas-service

management:
  endpoints:
    web:
      exposure:
        include: health,info  # Expose these endpoints
  endpoint:
    health:
      show-details: always
