server:
  port: ${PORT:0}

spring:
  application:
    name: rack-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME}
    instance-id: ${HOSTNAME}:${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info