server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: reportes-service

management:
  endpoints:
    web:
      exposure:
        include: health,info