# Correct YAML indentation

server:
  port: 9090

  
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

spring:
  application:
    name: reservacomprobante-service
  datasource:
    url: jdbc:postgresql://reservacomprobante-db::5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: tomas.carcamo.g@usach.cl
    password: ttvskbgtqjguqmbq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
