# Correct YAML indentation

server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: reservacomprobante-service
  datasource:
    url: jdbc:postgresql://postgres:5432/reservacomprobante
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mail:
    host: smtp.gmail.com
    port: 587
    username: tomas.carcamo.g@usach.cl
    password: ttvskbgtqjguqmbq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
