server:
  port: ${PORT:0}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.application.name}
    instance_id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: tarifas-especiales-service
  datasource:
    url: jdbc:postgresql://postgres:5432/tarifas_especiales
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  # Change from update to create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  cloud:
    config:
      enabled: true